apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 997208471343.dkr.ecr.ap-south-1.amazonaws.com/micro-gateway:latest # Update with your image
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: micro-config
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: LoadBalancer # Expose gateway to the internet
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: gateway

