apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: 997208471343.dkr.ecr.ap-south-1.amazonaws.com/micro-product-service:latest
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: micro-config
          readinessProbe:
            httpGet:
              path: /health
              port: 3002

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  ports:
    - port: 3002
  selector:
    app: product-service
