apiVersion: v1
kind: ConfigMap
metadata:
  name: micro-config
data:
  NODE_ENV: production
  GATEWAY_PORT: "3000"
  USER_SERVICE_PORT: "3001"
  PRODUCT_SERVICE_PORT: "3002"
  ORDER_SERVICE_PORT: "3003"
  USER_SERVICE_URL: "http://user-service:3001"
  PRODUCT_SERVICE_URL: "http://product-service:3002"
  ORDER_SERVICE_URL: "http://order-service:3003"
  MONGO_URI: "mongodb://mongodb:27017"
  MONGO_DB_USER: "micro_users"
  MONGO_DB_PRODUCT: "micro_products"
  MONGO_DB_ORDER: "micro_orders"
  JWT_EXPIRES_IN: "24h"

---
apiVersion: v1
kind: Secret
metadata:
  name: micro-secrets
type: Opaque
data:
  # echo -n 'your-super-secret-key-change-in-production' | base64
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
