name: Manual Microservice Build

on:
  # This allows you to trigger the build manually from the GitHub UI
  workflow_dispatch:
    inputs:
      service:
        description: 'Select the service to build and push'
        required: true
        default: 'gateway'
        type: choice
        options:
          - gateway
          - user-service
          - product-service
          - order-service

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: ${{ github.event.inputs.service }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: services/${{ github.event.inputs.service }}/package-lock.json

      - name: Install Dependencies
        run: |
          cd services/$SERVICE_NAME
          npm install

      - name: Run Tests
        run: |
          cd services/$SERVICE_NAME
          npm test || echo "No tests found"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Image to AWS ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: micro-${{ github.event.inputs.service }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest services/$SERVICE_NAME
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
